optuna:
  study_name: ti_online_optuna_slippery_sac_v4
  direction: maximize
  n_trials: 20

  env_id: slippery
  method: CRTR
  metric: auc_success
  total_steps: 50000
  pruner: median
  prune_every: 5000
  prune_min_steps: 10000
  pruner_startup_trials: 5

  search_space:
    bonus_scale: [0.05, 2.0]
    bonus_beta: [0.1, 2.0]
    bonus_lambda: [0.1, 2.0]
    q_lr: [1.0e-4, 5.0e-4]
    eps_decay_steps: [30000, 150000]
    rep_update_every: [1, 6]
    update_every: [2, 8]
